[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
pythonpath = .
addopts =
    --html=reports/report.html
    --self-contained-html
    --capture=tee-sys
    --cov=framework
    --cov=mock_server
    --cov-report=term-missing
    --cov-fail-under=85
log_cli = true
log_cli_level = INFO
