name: QA Automation Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create report folder
        run: mkdir -p reports

      - name: Launch Environment (Docker + SSL)
        run: |
          mkdir -p certs
          openssl req -x509 -newkey rsa:4096 -keyout certs/key.pem -out certs/cert.pem -sha256 -days 365 -nodes -subj "/CN=localhost"
          docker compose up -d --build
          sleep 30

      - name: Test Nginx endpoint
        run: curl -vk https://localhost:5000/chat

      - name: Run Functional Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest tests --html=reports/report.html --self-contained-html

      - name: Install JMeter
        run: |
          wget -q https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Run Performance Tests
        run: |
          rm -rf jmeter_dashboard
          ./apache-jmeter-5.6.3/bin/jmeter \
            -n \
            -t jmeter_test_plan.jmx \
            -l results.jtl \
            -e \
            -o jmeter_dashboard \
            -Djsse.enableSNIExtension=false

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: full-qa-reports
          path: |
            reports/report.html
            jmeter_dashboard/
            results.jtl
